[book]
authors = ["waku-org"]
language = "en"
multilingual = false
src = "src"
title = "Waku Simulator Book"
description = "A brief description of your book."

[output.html]
git-repository-url = "https://github.com/waku-org/waku-simulator"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/waku-org/waku-simulator/master/guide/{path}"
