{
 "title": "Nim GC performance testing",
 "description": "Measuring performance of request/response nwaku protocols.\nLightpush, Filter and Store request processing times are measured.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "nwaku_instance",
    "label": "nwaku-instance",
    "query": {
     "query": "label_values(libp2p_peers{instance=~\".*servicenode.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Lightpush performance in scope of Nim Memory Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Lightpush and filter request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(waku_service_requests_total{service = \"/vac/waku/lightpush/2.0.0-beta1\", instance=\"servicenode:8008\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "rate(waku_service_requests_total{service=\"/vac/waku/filter-subscribe/2.0.0-beta1\", instance=\"servicenode:8008\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Heap allocation per objects",
   "type": "timeseries",
   "gridPos": { "h": 30, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{instance=\"servicenode:8008\"}",
     "legendFormat": "{{type_name}}"
    }
   ]
  },
  {
   "title": "Lightpush request performance",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(le) (increase(waku_service_request_handling_duration_seconds_bucket{instance=\"servicenode:8008\", service=\"/vac/waku/lightpush/2.0.0-beta1\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "NIM GC Memory",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{instance=\"servicenode:8008\"}",
     "legendFormat": "Nim gc mem bytes of {{instance}}"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{instance=\"servicenode:8008\"}",
     "legendFormat": "Nim gc occupied bytes of {{instance}}"
    },
    {
     "expr": "nim_gc_heap_instance_occupied_summed_bytes{instance=\"servicenode:8008\"}",
     "legendFormat": "Nim gc heap bytes of {{instance}}"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"servicenode:8008\"}",
     "legendFormat": "Process virtual memory of {{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"servicenode\"}[$__rate_interval])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"servicenode\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  { "title": "General load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } }
 ]
}