{
 "title": "nwaku-store-monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Store peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "waku_store_peers", "legendFormat": "{{instance}}_{{__name__}}" }
   ]
  },
  {
   "title": "Store queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "waku_store_queries", "legendFormat": "{{instance}}_{{__name__}}" }
   ]
  },
  {
   "title": "Legacy store queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "waku_legacy_store_queries", "legendFormat": "{{instance}}_{{__name__}}" }
   ]
  }
 ]
}