{
 "title": "nwaku-monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "nwaku_instance",
    "query": {
     "query": "label_values(libp2p_peers, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Mix Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mix msgs Rcvd (Intermediate)",
   "type": "stat",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mix_messages_recvd_total{type=\"Intermediate\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mix msgs Rcvd (Exit)",
   "type": "stat",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mix_messages_recvd_total{type=\"Exit\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LP msgs Recvd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "targets": [
    { "expr": "waku_lightpush_v3_messages", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Relay msgs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 14 },
   "targets": [
    { "expr": "waku_node_messages_total", "legendFormat": "{{instance}}_{{__name__}}" }
   ]
  },
  {
   "title": "Mix Msgs Recvd(Intermediate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "mix_messages_recvd{type=\"Intermediate\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mix Msgs Recvd(Exit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "mix_messages_recvd{type=\"Exit\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mix Msgs Fwd",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "targets": [
    { "expr": "mix_messages_forwarded", "legendFormat": "{{instance}}_{{__name__}}" }
   ]
  },
  {
   "title": "Mix Msgs Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 30 },
   "targets": [
    { "expr": "mix_messages_error", "legendFormat": "{{instance}}_{{__name__}}" }
   ]
  },
  {
   "title": "LP Mix Sim msgs sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 38 },
   "targets": [
    { "expr": "lp_mix_success", "legendFormat": "{{instance}}_{{__name__}}" }
   ]
  },
  {
   "title": "Others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 21, "x": 0, "y": 47 },
     "options": {
      "content": "# Single Node (Select nwaku-instance)"
     }
    },
    {
     "title": "Message distrubution %/kBytes (Last Hour)",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(waku_histogram_message_size_bucket{instance=\"[[nwaku_instance]]\"}[1h])/scalar(rate(waku_histogram_message_size_count{instance=\"[[nwaku_instance]]\"}[1h]))*100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connected Streams",
     "type": "stat",
     "gridPos": { "h": 10, "w": 11, "x": 10, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "waku_streams_peers{instance=\"[[nwaku_instance]]\"}",
       "legendFormat": "{{instance}}_{{protocol}}_{{direction}}"
      }
     ]
    },
    {
     "title": "Connected Protocols",
     "type": "stat",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 59 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "waku_connected_peers{instance=\"[[nwaku_instance]]\"}",
       "legendFormat": "{{instance}}_{{protocol}}_{{direction}}"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "stat",
     "gridPos": { "h": 8, "w": 11, "x": 10, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nim_gc_mem_bytes{}", "legendFormat": " " }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 21, "x": 0, "y": 67 }, "options": { "content": "# Global View (All Nodes)" } },
    {
     "title": "Connected Peers",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "libp2p_peers", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Inbound Peers",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "waku_connected_peers{direction=\"Inbound\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Outbound Peers",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 14, "y": 69 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "waku_connected_peers{direction=\"Outbound\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Reachability",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "libp2p_autonat_reachability_confidence{reachability=\"Reachable\"}",
       "legendFormat": "{{reachability}}"
      }
     ]
    },
    {
     "title": "Num PubSub Topics",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 76 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "libp2p_pubsub_topics", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "libp2p traffic (in)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(libp2p_network_bytes_total{direction=\"in\"}[$__rate_interval])",
       "legendFormat": "{{instance}}_{{direction}}"
      }
     ]
    },
    {
     "title": "libp2p traffic (out)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 11, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(libp2p_network_bytes_total{direction=\"out\"}[$__rate_interval])",
       "legendFormat": "{{instance}}_{{direction}}"
      }
     ]
    },
    {
     "title": "total traffic cadvisor (in)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total[1m])",
       "legendFormat": "{{container_label_com_docker_compose_service}}_{{container_label_com_docker_compose_container_number}}"
      }
     ]
    },
    {
     "title": "Libp2p Open Streams",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 11, "y": 92 },
     "targets": [
      {
       "expr": "libp2p_open_streams{instance=\"[[nwaku_instance]]\"}",
       "legendFormat": "{{instance}}_{{type}}_{{dir}}"
      }
     ]
    },
    {
     "title": "Rejected Messages/second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "(increase(waku_msg_validator_signed_outcome_total{result=\"Reject\"}[1m]))/60",
       "legendFormat": "{{instance}}_{{result}}"
      }
     ]
    },
    {
     "title": "total traffic cadvisor (out)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total[1m])",
       "legendFormat": "{{container_label_com_docker_compose_service}}_{{container_label_com_docker_compose_container_number}}"
      }
     ]
    },
    {
     "title": "Average msg size (kBytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 108 },
     "targets": [
      {
       "expr": "waku_histogram_message_size_sum/waku_histogram_message_size_count",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Acepted Messages/second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 110 },
     "targets": [
      {
       "expr": "(increase(waku_msg_validator_signed_outcome_total{result=\"Accept\"}[1m]))/60",
       "legendFormat": "{{instance}}_{{result}}"
      }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 116 },
     "targets": [
      { "expr": "libp2p_peers", "legendFormat": "{{instance}}_{{__name__}}" }
     ]
    },
    {
     "title": "Messages/second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 118 },
     "targets": [
      {
       "expr": "(increase(waku_node_messages_total[1m]))/60",
       "legendFormat": "{{instance}}_{{type}}"
      }
     ]
    },
    {
     "title": "Peer Store Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 124 },
     "targets": [
      { "expr": "waku_peer_store_size", "legendFormat": "{{instance}}_{{__name__}}" }
     ]
    },
    {
     "title": "Bad Peer Disconnection",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 126 },
     "targets": [
      {
       "expr": "libp2p_gossipsub_bad_score_disconnection_total",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failed Pubsub Messages/Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 132 },
     "targets": [
      {
       "expr": "(increase(libp2p_gossipsub_failed_publish_total[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Published Pubsub Messages/Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 134 },
     "targets": [
      {
       "expr": "(increase(libp2p_pubsub_messages_published_total[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GossipSub Low Peers Topic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 140 },
     "targets": [
      {
       "expr": "libp2p_gossipsub_low_peers_topics",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GossipSub Invalid Topic Subscriptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 142 },
     "targets": [
      {
       "expr": "libp2p_gossipsub_invalid_topic_subscription_total",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GossipSub Total Received/Minute",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 148 },
     "targets": [
      {
       "expr": "(increase(libp2p_gossipsub_received_total[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GossipSub Healthy Topics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 150 },
     "targets": [
      {
       "expr": "libp2p_gossipsub_healthy_peers_topics",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "LibP2P Dials",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 156 },
     "targets": [
      {
       "expr": "libp2p_total_dial_attempts_total{}",
       "legendFormat": "{{instance}}__attempts"
      },
      { "expr": "libp2p_failed_dials_total{}", "legendFormat": "{{instance}}__failed" },
      {
       "expr": "libp2p_successful_dials_total{}",
       "legendFormat": "{{instance}}__success"
      }
     ]
    },
    {
     "title": "Reachability State",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 158 },
     "targets": [
      {
       "expr": "libp2p_autonat_reachability_confidence{}",
       "legendFormat": "{{instance}}__{{reachability}}"
      }
     ]
    },
    {
     "title": "Nim Total Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "nim_gc_mem_bytes{}", "legendFormat": "{{instance}}_{{__name__}}" }
     ]
    },
    {
     "title": "Peers Per Topic Mesh",
     "type": "timeseries",
     "description": "Careful with this when using more than one topic, as all values will be added in \"other\" unless nimlibp2p is compiled with the appropriate flags",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 166 },
     "targets": [
      {
       "expr": "libp2p_gossipsub_peers_per_topic_mesh",
       "legendFormat": "{{instance}}_topic_{{topic}}"
      }
     ]
    },
    {
     "title": "Version",
     "type": "table",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 172 },
     "targets": [
      { "expr": "waku_version", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Container Mem Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes",
       "legendFormat": "{{container_label_com_docker_compose_service}}_{{container_label_com_docker_compose_container_number}}"
      }
     ]
    },
    {
     "title": "RLN Registered Memberships",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 180 },
     "targets": [
      {
       "expr": "waku_rln_number_registered_memberships",
       "legendFormat": "{{instance}}_{{__name__}}"
      }
     ]
    },
    {
     "title": "CPU (Unsure what)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 182 },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total[1m])",
       "legendFormat": "{{container_label_com_docker_compose_service}}_{{container_label_com_docker_compose_container_number}}"
      }
     ]
    },
    {
     "title": "RLN Proof Verification (seconds)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 188 },
     "targets": [
      {
       "expr": "waku_rln_proof_verification_duration_seconds",
       "legendFormat": "{{instance}}_{{__name__}}"
      }
     ]
    },
    {
     "title": "RLN Proof Generation (seconds)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 190 },
     "targets": [
      {
       "expr": "waku_rln_proof_generation_duration_seconds",
       "legendFormat": "{{instance}}_{{__name__}}"
      }
     ]
    },
    {
     "title": "RLN Credentials Import (seconds)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 196 },
     "targets": [
      {
       "expr": "waku_rln_membership_credentials_import_duration_seconds",
       "legendFormat": "{{instance}}_{{__name__}}"
      }
     ]
    },
    {
     "title": "RLN Membership Insertion (seconds)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 198 },
     "targets": [
      {
       "expr": "waku_rln_membership_insertion_duration_seconds",
       "legendFormat": "{{instance}}_{{__name__}}"
      }
     ]
    },
    {
     "title": "RLN Proof Verification Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 204 },
     "targets": [
      {
       "expr": "waku_rln_proof_verification_total_total",
       "legendFormat": "{{instance}}_{{__name__}}"
      }
     ]
    },
    {
     "title": "RLN Messages Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 206 },
     "targets": [
      { "expr": "waku_rln_messages_total_total", "legendFormat": "{{instance}}_{{__name__}}" }
     ]
    },
    {
     "title": "RLN Instance Creation (seconds)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 212 },
     "targets": [
      {
       "expr": "waku_rln_instance_creation_duration_seconds",
       "legendFormat": "{{instance}}_{{__name__}}"
      }
     ]
    },
    {
     "title": "RLN Spam Messages Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 214 },
     "targets": [
      {
       "expr": "waku_rln_spam_messages_total_total",
       "legendFormat": "{{instance}}_{{__name__}}"
      }
     ]
    },
    {
     "title": "RLN Invalid Messages Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 220 },
     "targets": [
      {
       "expr": "waku_rln_invalid_messages_total_total",
       "legendFormat": "{{instance}}_{{__name__}}"
      }
     ]
    },
    {
     "title": "RLN Valid Messages Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 222 },
     "targets": [
      {
       "expr": "waku_rln_valid_messages_total_count",
       "legendFormat": "{{instance}}_{{__name__}}"
      }
     ]
    }
   ]
  }
 ]
}