{
 "title": "Non-relay (req/resp) protocol performance",
 "description": "Measuring performance of request/response nwaku protocols.\nLightpush, Filter and Store request processing times are measured.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "nwaku_instance",
    "label": "nwaku-instance",
    "query": {
     "query": "label_values(libp2p_peers{instance=~\".*servicenode.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Lightpush / Filter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lightpush request performance",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (increase(waku_service_request_handling_duration_seconds_bucket{instance=\"$nwaku_instance\", service=\"/vac/waku/lightpush/2.0.0-beta1\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Lightpush and filter request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(waku_service_requests_total{service = \"/vac/waku/lightpush/2.0.0-beta1\", instance=\"servicenode:8008\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "rate(waku_service_requests_total{service=\"/vac/waku/filter-subscribe/2.0.0-beta1\", instance=\"servicenode:8008\"}[$__rate_interval])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Filter subscribe performance",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(le) (increase(waku_service_request_handling_duration_seconds_bucket{instance=\"$nwaku_instance\", service=\"/vac/waku/filter-subscribe/2.0.0-beta1\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Filter message handling performance",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(le) (increase(waku_filter_handle_message_duration_seconds_bucket{instance=\"servicenode:8008\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Store query performance",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "sum by(le) (increase(waku_service_request_handling_duration_seconds_bucket{instance=\"servicenode:8008\", service=\"/vac/waku/store-query/3.0.0\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Store request rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "targets": [
      {
       "expr": "rate(waku_service_requests_total{service=\"/vac/waku/store-query/3.0.0\", instance=\"servicenode:8008\"}[$__rate_interval])",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  { "title": "General load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Libp2p traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_network_bytes_total{instance=\"$nwaku_instance\"}[$__rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"servicenode\"}[$__rate_interval])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{instance=\"servicenode:8008\"}",
     "legendFormat": "{{type_name}}"
    }
   ]
  },
  {
   "title": "NIM GC Memory",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_mem_bytes{instance=\"$nwaku_instance\"}",
     "legendFormat": "Nim gc mem bytes of {{instance}}"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{instance=\"servicenode:8008\"}",
     "legendFormat": "Nim gc occupied bytes of {{instance}}"
    },
    {
     "expr": "nim_gc_heap_instance_occupied_summed_bytes{instance=\"servicenode:8008\"}",
     "legendFormat": "Nim gc heap bytes of {{instance}}"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=\"servicenode:8008\"}",
     "legendFormat": "Process virtual memory of {{instance}}"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"servicenode\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  }
 ]
}