route:
  group_by: ['alertname']
  group_wait: 60s
  group_interval: 5m
  repeat_interval: 1d
  receiver: 'discord'

receivers:
  - name: 'discord'
    discord_configs:
      - webhook_url: # TO DO: fill discord webhook